MODULE_NAME="iOS / iPad Backups"
MODULE_DESCRIPTION="Device backups under ~/Library/Application Support/MobileSync/Backup. HIGH RISK — backups are not auto-recoverable. The Smart Advisor surfaces specific old backups; this module is rarely run as a default."
MODULE_RISK="high"
MODULE_CATEGORY="dev"
MODULE_PATHS=("$HOME/Library/Application Support/MobileSync/Backup")
MODULE_AGE_DAYS=365
MODULE_NOTES="Strongly recommend using the Advisor (advisor.sh) to review specific backups instead of bulk-clearing."
MODULE_NAME_ZH="iOS / iPad 备份"
MODULE_DESCRIPTION_ZH="MobileSync 下的设备备份。高风险 — 删了不能自动恢复。建议用 Advisor 查看具体备份。"
